DROP TABLE USER_ROLES IF EXISTS;
DROP TABLE USERS IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE USERS
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    email      VARCHAR(255)         NOT NULL,
    password   VARCHAR(255)         NOT NULL,
    enabled    BOOLEAN DEFAULT TRUE NOT NULL,
    first_name VARCHAR(255)         NOT NULL,
    last_name  VARCHAR(255)         NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
    ON USERS (email);

CREATE TABLE USER_ROLES
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

INSERT INTO USERS (email, password, first_name, last_name)
VALUES ('user@gmail.com', '{noop}password', 'Ivan', 'Ivanov'),
       ('admin@gmail.com', '{noop}password', 'Boris', 'Borisov');

INSERT INTO USER_ROLES (role, user_id)
VALUES ('USER', 100000),
       ('ADMIN', 100001),
       ('USER', 100001);
